name: Python Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  FORCE_COLOR: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
        architecture: [x64]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Run unit tests
        run: uv run pytest tests/units -v --cov --cov-report term-missing
